name: package

on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'test_package/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/package.yml'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test_package/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/package.yml'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@main
    with:
      platform_wasm: true
    secrets: inherit

  npm-package:
    needs: [ conan-package ]
    # Run the job for: 1) push to 'main' or branches starting with 'NP-', or 2) merged pull requests targeting 'main'.
    if: ${{(github.event_name == 'push' && (github.ref_name == 'main' || startsWith(github.ref_name, 'NP-'))) || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.base_ref == 'main' && github.merge_commit_sha)}}
    uses: ultimaker/cura-workflows/.github/workflows/npm-package.yml@main
    with:
      package_version_full: ${{ needs.conan-package.outputs.package_version_full }}
    secrets: inherit
